#!/usr/bin/python
# NeutronOVSBasicDeployment
"""Amulet tests on a basic neutron-openvswitch deployment on trusty-liberty."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-liberty',
                                           source='cloud:trusty-updates/liberty')
    deployment.run_tests()
