#!/usr/bin/python
# NeutronOVSBasicDeployment
"""Amulet tests on a basic neutron-openvswitch deployment on trusty-mitaka."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-mitaka',
                                           source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
