#!/usr/bin/python

"""Amulet tests on a basic neutron-openvswitch deployment on wily-liberty."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='wily')
    deployment.run_tests()
