#!/usr/bin/python

"""Amulet tests on a basic neutron-openvswitch deployment on xenial-mitaka."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='xenial')
    deployment.run_tests()
